baseurl = "http://www.linedotline.studio/"
languageCode = "en-us"
style = "default"
theme = "hugo-creative-portfolio-theme"
title = "line-dot-line"
[params]
copyright = "&copy;2016 Your name or company"
description = "Describe your website"
email = "carly@linedotline.com"
sidebarabout = ["Filmmaker, animator.", "Based in Los Angeles"]
style = "default"
[params.social]
email = "email@example.com"
facebook = "full page or profile url in facebook"
github = "full profile url in github"
googleplus = "full profile url in googleplus"
instagram = "full profile url in instagram"
linkedin = "full profile url in linkedin"
stackoverflow = "full profile url in stackoverflow"
twitter = "full profile url in twitter"
[[params.navlinks]]
name = "Home"
url = ""
[[params.navlinks]]
name = "About"
url = "about/"
[[params.navlinks]]
name = "Get in touch"
url = "contact/"
